# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Story1
Story.create(title:"It Was A Dark And Stormy Knight",every_word:true,body:"He looked like any other man sworn to defend the kingdom:  strong, determined, and a force to be reckoned with.  However, he had one minor distinguishing feature:  a tiny storm cloud hovering above his head.")
#Story2
Story.create(title:"An Inconvenient Invasion",every_word:true,body:"Fires raged and roiled over everything Emma saw.  She heard the metal frames of nearby automobiles scream in violation as the incensed inferno sadistically twisted them into shapes they were never meant to resemble.  She swung around, looking for anyone else who made it out, but the only movement was the shimmering air from the overwhelming heat.  As she stumbled towards the park across the street, away from the flames, she realized if They had decided to come a day or two later, she would have made her job interview and possibly have had health insurance before the invasion happened.  Half-deliriously she closed her eyes and chuckled to herself…and caught the curb with her foot, crumpling face-first into the cool grass.  “This”, Emma thought, “is really just not my day”.")
#Story3
Story.create(title:"Twilight - Round Two",every_word:true,body:"\"Hello,\" said a quiet, musical voice. I looked up, stunned that he was speaking to me. He was sitting as far away from me as the desk allowed, but his chair was angled toward me. His hair was dripping wet, disheveled — even so, he looked like he'd just finished shooting a commercial for hair gel. His dazzling face was friendly, open, a slight smile on his flawless lips. But his eyes were careful. \"My name is Edward Cullen,\" he continued. \"I didn't have a chance to introduce myself last week. You must be Bella Swan.\" My mind was spinning with confusion. Had I made up the whole thing? He was perfectly polite now. I had to speak; he was waiting. But I couldn't think of anything conventional to say.")
#Story4
Story.create(title:"It’s Over",every_word:true,body:"I packed my bags and left that night.  You can love a person through almost anything, but this was the final straw.  I wasn’t going to stand for it any longer.")
#Story5
Story.create(title:"The Sheriff’s Secret",every_word:true,body:"All the accolades at the saloon, the gentlemen tipping their hats in the street while ladies blushed and curtsied; all the respect he garnered around town was all based on a lie.  Yes, Sheriff Ambrose had collared twenty three of the most wanted bandits since he started at his post here, but while he had brought every one of the captured criminals into the station, no one could imagine the truth:  the Sheriff’s horse had done all the work.")
#Story6
Story.create(title:"Not Quite Another Day At School",every_word:true,body:"Brian jolted awake.  \"Mr. Cambell!\"  Brian opened his eyes to see a blurry figure that looked vaguely like his 2nd period English teacher looking directly at him.  \"Mr. Cambell!  I trust William Shakespeare, one of the greatest playwrights this world has ever been graced to host, is not the reason you are sleeping in my class this morning?\"  Brian thought for a second, then spoke \"Not…the only reason, Miss Peters.\"  The class tittered.  He blinked a couple more times to see his teacher’s formerly featureless face resolve into what must have been the tightest pursing of the lips he ever remembered witnessing.  And his still-sleepy grin didn’t seem to be helping.  Miss Peters finally opened her mouth, \"Detention, Brian.  Let\’s have you stay an extra hour after school to make sure you didn\’t miss any essential components of Troilus and Cressida during your nap.  Now class, let\’s ensure we don\’t have anyone else joining Brian today.\"  He sighed.  Oh well, perhaps she\’d let him get started on some homework if he apologized.  He looked out the window.  With all the snow swirling around it\’s not like staying in school a little longer was the worst thing that could happen to him.  Plus, it still looked about 20 degrees-Brian looked further left and sat up straight.  Out on south soccer field, he saw what could only be described as")
